# A single CI script with github workflow
name: Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install qibo
    - name: Test package
      run: |
        python main.py
        python main.py --collisions 2
        python circuit-specifications/sponge_toy_main.py
        python circuit-specifications/sponge_full_main.py
        python circuit-specifications/blake_toy_main.py
        python circuit-specifications/blake_full_main.py
